---
- hosts: lxc
  become: true
  become_user: root

  tasks:
  - name: install python-lxc package
    apt:
      name: python-lxc
      state: latest
  
  - name: deploy "test" container
    lxc_container:
      template: ubuntu
      name: "test"
      container_config:
      - "lxc.mount.entry = /var/lib/lxc/shared mnt none bind 0 0"
