---
- hosts: lxc
  become: true
  become_user: root

  tasks:
  - name: install python-lxc package
    apt:
      name: python-lxc
      state: latest
  
  - name: unmount CephFS shared directory
    mount:
      src: daisy,eric,frank:/shared
      fstype: ceph
      opts: secretfile=/etc/ceph/cephfs.secret,name=cephfs
      name: /var/lib/lxc/shared
      state: unmounted

  - name: create shared LXC directory
    file:
      path: /var/lib/lxc
      state: directory
      owner: root
      group: root

  - name: mount CephFS LXC directory
    mount:
      src: daisy,eric,frank:/lxc
      fstype: ceph
      opts: secretfile=/etc/ceph/cephfs.secret,name=cephfs
      name: /var/lib/lxc
      state: mounted

- hosts: alice
  become: true
  become_user: root
  
  tasks:
  - name: deploy "ha" container
    lxc_container:
      template: ubuntu
      name: "ha"
