---
- hosts: lxc
  become: true
  become_user: root

  tasks:
  - name: create shared LXC directory
    file:
      path: /var/lib/lxc/shared
      state: directory
      owner: root
      group: root

  - name: mount CephFS shared directory
    mount:
      src: daisy,eric,frank:/shared
      fstype: ceph
      opts: secretfile=/etc/ceph/cephfs.secret,name=cephfs,_netdev
      name: /var/lib/lxc/shared
      state: mounted
